export const postData = [
  {
    id: 1,
    username: 'ayush_verma_13',
    fullName: 'Ayush Verma',
    profilePic: 'https://scontent.fbho4-4.fna.fbcdn.net/v/t39.30808-6/347823893_940297803683423_4736240409875839683_n.jpg?_nc_cat=101&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=xdIx_8veQVAAX9oNdVm&_nc_ht=scontent.fbho4-4.fna&oh=00_AfA2oy_fu7wyrwqQWlX0YiG4UOiz93ab62wYBCjOndYw1Q&oe=649C2762',
    title: 'First Post',
    content: 'Lord Ganesha is the remover of obstacles and the god of beginnings. He is worshipped before starting any new endeavor.',
    godName: 'Ganesha',
    imageUrl: 'https://godhindus.com/wp-content/uploads/2023/05/hd-wallpaper-lord-ganesh.jpg',
    likes: 10,
    comments: [
      {
        id: 1,
        userName: 'riya_sharma',
        userId: '123',
        fullName: 'Riya Sharma',
        content: 'Great post!',
        likesOfComment: 5,
      },
      {
        id: 2,
        userName: 'vikram_singh',
        userId: '456',
        fullName: 'Vikram Singh',
        content: 'I love Lord Ganesha!',
        likesOfComment: 3,
      },
    ],
  },
  {
    id: 2,
    username: 'priya_gupta',
    fullName: 'Priya Gupta',
    profilePic: 'https://media.licdn.com/dms/image/C4D03AQEhipmxvOz8rg/profile-displayphoto-shrink_800_800/0/1650488111982?e=1693440000&v=beta&t=pRIjlvTvllqPsZPesTyeKFZMwze5aQ2lTzrlLAUXP2s',
    title: 'Second Post',
    content: 'Goddess Lakshmi is the goddess of wealth, prosperity, and fortune. She is worshipped for financial success and abundance.',
    godName: 'Lakshmi',
    imageUrl: 'https://www.bhaktiphotos.com/wp-content/uploads/2018/04/Devi-Goddess-Lakshmi-Shubh-Labh.jpg',
    likes: 5,
    comments: [
      {
        id: 1,
        userName: 'rajesh_sharma',
        userId: '789',
        fullName: 'Rajesh Sharma',
        content: 'Beautiful!',
        likesOfComment: 2,
      },
      {
        id: 2,
        userName: 'ananya_patel',
        userId: '012',
        fullName: 'Ananya Patel',
        content: 'Goddess Lakshmi blesses us with prosperity.',
        likesOfComment: 1,
      },
    ],
  },
  {
    id: 3,
    username: 'sandeep_verma',
    fullName: 'Sandeep Verma',
    profilePic: 'https://media.licdn.com/dms/image/C4E03AQFxk2ZoLZb-Pg/profile-displayphoto-shrink_800_800/0/1596682043090?e=1693440000&v=beta&t=SYY2L6WmxObdWyO9p-Jg6RxZawvvy0Tt-5ytxujNR7E',
    title: 'Third Post',
    content: 'Lord Shiva is the supreme god, the destroyer of evil, and the transformer. He is worshipped for spiritual enlightenment and inner peace.',
    godName: 'Shiva',
    imageUrl: 'https://www.wallsnapy.com/img_gallery/top-lord-shiva-images-hd-5795326.jpg',
    likes: 15,
    comments: [
      {
        id: 1,
        userName: 'neha_gupta',
        userId: '345',
        fullName: 'Neha Gupta',
        content: 'Lord Shiva is mighty!',
        likesOfComment: 7,
      },
    ],
  },
  // Add more post objects as needed
];
